import "./globals.css";

interface Metadata {
  title: string;
  description: string;
}

export const metadata: Metadata = {
  title: "Budgetwise",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="overflow-hidden h-screen">
        {children}
      </body>
    </html>
  );
}