import Navbar from "@/components/common/Navbar";
import "./globals.css";

interface Metadata {
  title: string;
  description: string;
}

export const metadata: Metadata = {
  title: "Budgetwise",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="md:overflow-hidden min-h-screen bg-background py-8 relative">
        {children}
        <Navbar />
      </body>
    </html>
  );
}