import "./globals.css";



export const metadata = {
  title: "Budgetwise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-hidden"
      >
        {children}
      </body>
    </html>
  );
}
